import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { decodePlannerInput } from "@/lib/planner/encode";
import { buildOutline } from "@/lib/planner/engine";
import { ButtonLink } from "@/components/ui/Button";
import { Eyebrow } from "@/components/ui/Eyebrow";
import { SystemOutlineCard } from "@/components/planner/SystemOutlineCard";

export const metadata: Metadata = {
  title: "Shared system outline",
  description: "A read-only system outline generated by the Market Analytica project planner.",
  robots: { index: false },
};

/** Read-only shared outline — SPEC.md §9.5. No email required to view. */
export default async function SharedPlannerPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;
  const input = decodePlannerInput(token);
  if (!input) notFound();
  const outline = buildOutline(input);

  return (
    <section className="section-pad">
      <div className="container-site max-w-3xl space-y-8">
        <header className="space-y-4">
          <Eyebrow>Shared outline · read-only</Eyebrow>
          <h1 className="text-[clamp(2.25rem,4.5vw,3.5rem)]">System outline</h1>
        </header>
        <SystemOutlineCard outline={outline} />
        <div className="flex flex-wrap items-center gap-4">
          <ButtonLink href={`/apply?planner=${token}`}>Apply for a Custom Build</ButtonLink>
          <Link href="/planner" className="text-sm text-mute underline underline-offset-4 hover:text-paper">
            Run the planner with your own inputs
          </Link>
        </div>
      </div>
    </section>
  );
}
